import { buildModule, type CourseModule } from "@/lib/course-model";

export const pythonModules: CourseModule[] = [
  buildModule(
    {
      id: "py-control-flow",
      title: "Loops and functions",
      description: "Repeat work, package behavior, and understand where names live.",
      level: "Foundations",
    },
    [
      {
        id: "py-for-loops",
        concept: "Loops",
        teachTitle: "Repeat an action with for",
        teachBody: "A for loop visits each item in a sequence. The indented block runs once for every item, and the loop variable points to the current item.",
        takeaway: "Use for when you want to visit each item in a collection.",
        exampleTitle: "Trace each visit",
        exampleBody: "The loop visits 1, 2, and 3 in order and adds each number to total.",
        sample: "total = 0\nfor number in [1, 2, 3]:\n    total += number\nprint(total)  # 6",
        question: "What does this loop print?",
        questionSample: "for letter in \"go\":\n    print(letter)",
        options: ["g and then o", "go once", "0 and then 1"],
        answer: 0,
        explanation: "A string is a sequence of characters, so the loop prints g and then o on separate lines.",
        hint: "Ask what the next individual item in the string is.",
      },
      {
        id: "py-while-loops",
        concept: "Loops",
        teachTitle: "Repeat while a condition is true",
        teachBody: "A while loop checks its condition before each repetition. Something inside the loop must eventually change that condition or the loop may never end.",
        takeaway: "A while loop needs a condition and a path toward stopping.",
        exampleTitle: "Count toward the exit",
        exampleBody: "count grows after every print. When it reaches 3, count < 3 becomes False and the loop stops.",
        sample: "count = 0\nwhile count < 3:\n    print(count)\n    count += 1",
        question: "How many times does the loop body run?",
        questionSample: "energy = 3\nwhile energy > 0:\n    energy -= 1",
        options: ["2 times", "3 times", "Forever"],
        answer: 1,
        explanation: "energy starts at 3 and becomes 2, 1, then 0 across three repetitions. At 0 the condition is false.",
        hint: "Write the value of energy after each repetition.",
      },
      {
        id: "py-functions",
        concept: "Functions",
        teachTitle: "Name a reusable behavior",
        teachBody: "A function groups instructions behind a name. Parameters receive input and return sends a result back to the caller.",
        takeaway: "Parameters bring values in; return sends a value out.",
        exampleTitle: "Call the same idea with new input",
        exampleBody: "The function definition runs only when greet is called. The argument becomes the name parameter.",
        sample: "def greet(name):\n    return f\"Hello, {name}\"\n\nmessage = greet(\"Maya\")\nprint(message)",
        question: "What value does double(4) return?",
        questionSample: "def double(number):\n    return number * 2",
        options: ["4", "8", "None"],
        answer: 1,
        explanation: "The argument 4 becomes number, and the function returns 4 × 2, which is 8.",
        hint: "Replace number with 4 in the return expression.",
      },
    ],
  ),
  buildModule(
    {
      id: "py-collections",
      title: "Python collections",
      description: "Organize related values with lists, dictionaries, tuples, and sets.",
      level: "Foundations",
    },
    [
      {
        id: "py-lists",
        concept: "Lists",
        teachTitle: "Keep an ordered, changeable collection",
        teachBody: "A list stores values in order. Indexes begin at zero, append adds an item, and negative indexes count backward from the end.",
        takeaway: "Lists preserve order and can grow or change.",
        exampleTitle: "Update one position",
        exampleBody: "Index 1 refers to the second item. Assigning to that index replaces only that value.",
        sample: "tasks = [\"read\", \"scroll\", \"code\"]\ntasks[1] = \"practice\"\nprint(tasks)",
        question: "What does topics[-1] return?",
        questionSample: "topics = [\"loops\", \"functions\", \"lists\"]",
        options: ["loops", "lists", "An error"],
        answer: 1,
        explanation: "Index -1 selects the final item in a list, which is lists.",
        hint: "Negative one means one position from the end.",
      },
      {
        id: "py-dictionaries",
        concept: "Dictionaries",
        teachTitle: "Look up values by meaningful keys",
        teachBody: "A dictionary maps unique keys to values. Keys describe what a value means and allow fast direct lookup without scanning positions.",
        takeaway: "Use a dictionary when values have natural labels or identifiers.",
        exampleTitle: "Read and update by key",
        exampleBody: "The string score identifies the value. Reassigning that key changes the stored score.",
        sample: "player = {\"name\": \"Adi\", \"score\": 10}\nplayer[\"score\"] += 5\nprint(player[\"score\"])  # 15",
        question: "Which expression safely returns 0 when points is missing?",
        options: ["player['points']", "player.get('points', 0)", "player.points or 0"],
        answer: 1,
        explanation: "dict.get accepts a default value and returns it when the requested key does not exist.",
        hint: "One dictionary method accepts both a key and a fallback.",
      },
      {
        id: "py-sets-tuples",
        concept: "Sets and tuples",
        teachTitle: "Choose uniqueness or immutability",
        teachBody: "A set keeps unique values without positional indexing. A tuple keeps an ordered sequence that cannot be changed after creation.",
        takeaway: "Sets answer membership and uniqueness questions; tuples represent fixed records.",
        exampleTitle: "Remove duplicates naturally",
        exampleBody: "Creating a set from a list keeps one copy of each distinct value.",
        sample: "tags = [\"python\", \"web\", \"python\"]\nunique_tags = set(tags)\nprint(len(unique_tags))  # 2",
        question: "Which collection best represents fixed latitude and longitude?",
        options: ["A tuple", "A set", "A changing list only"],
        answer: 0,
        explanation: "A two-value tuple preserves order and communicates that the coordinate pair should remain fixed.",
        hint: "The two positions have meaning and should not change.",
      },
    ],
  ),
  buildModule(
    {
      id: "py-intermediate",
      title: "Reliable Python",
      description: "Handle failures, organize code, work with files, and model behavior.",
      level: "Intermediate",
    },
    [
      {
        id: "py-errors",
        concept: "Exceptions",
        teachTitle: "Handle expected failures deliberately",
        teachBody: "Exceptions interrupt normal execution. A narrow try/except block can recover from a specific expected problem while letting unexpected bugs remain visible.",
        takeaway: "Catch the specific exception you know how to handle.",
        exampleTitle: "Turn invalid text into a useful response",
        exampleBody: "int raises ValueError for nonnumeric text. Catching that exact error lets the program choose a fallback.",
        sample: "try:\n    age = int(\"unknown\")\nexcept ValueError:\n    age = None",
        question: "Which exception should int('hello') be expected to raise?",
        options: ["ValueError", "KeyError", "FileNotFoundError"],
        answer: 0,
        explanation: "The string exists but has an invalid value for integer conversion, so Python raises ValueError.",
        hint: "The problem is the value of the string, not a missing key or file.",
      },
      {
        id: "py-files-modules",
        concept: "Files and modules",
        teachTitle: "Separate code and manage resources",
        teachBody: "Modules organize reusable Python code. Context managers such as with open(...) ensure resources are cleaned up even when work fails.",
        takeaway: "Import reusable behavior; use with for resources that must close.",
        exampleTitle: "Read a file safely",
        exampleBody: "The context manager opens the file, reads it, and closes it automatically when the block ends.",
        sample: "with open(\"notes.txt\", encoding=\"utf-8\") as file:\n    notes = file.read()",
        question: "Why is with open(...) preferred for basic file access?",
        options: ["It makes files permanent", "It closes the file automatically", "It converts every file to JSON"],
        answer: 1,
        explanation: "The context manager guarantees the file is closed when the block exits, including after many exceptions.",
        hint: "Think about cleanup after the indented block.",
      },
      {
        id: "py-oop",
        concept: "Object-oriented Python",
        teachTitle: "Keep related state and behavior together",
        teachBody: "A class describes how objects are built. Each instance receives its own state through self, while methods define behavior that uses that state.",
        takeaway: "A class is a blueprint; an instance is one concrete object.",
        exampleTitle: "Create two independent objects",
        exampleBody: "Each Counter instance owns a separate value even though both use the same class definition.",
        sample: "class Counter:\n    def __init__(self):\n        self.value = 0\n\n    def increment(self):\n        self.value += 1",
        question: "What does self represent inside an instance method?",
        options: ["The current object", "Every class in Python", "The imported module"],
        answer: 0,
        explanation: "self refers to the particular instance receiving the method call, giving access to that object's state.",
        hint: "Two instances can have different values. Which one is the method changing?",
      },
    ],
  ),
  buildModule(
    {
      id: "py-complexity-hashing",
      title: "Complexity and fast lookup",
      description: "Measure algorithm growth and solve common array, string, and hash-table problems.",
      level: "Intermediate",
    },
    [
      {
        id: "py-big-o",
        concept: "Big O",
        teachTitle: "Describe how work grows",
        teachBody: "Big O focuses on how runtime or memory changes as input grows. It ignores machine speed and small constants to compare algorithm shape.",
        takeaway: "One pass is usually O(n); nested full passes are usually O(n²).",
        exampleTitle: "Count the passes",
        exampleBody: "The loop visits each of n values once, so doubling the input roughly doubles the work.",
        sample: "def total(values):\n    result = 0\n    for value in values:\n        result += value\n    return result  # O(n)",
        question: "What is the usual time complexity of two full nested loops over n items?",
        options: ["O(1)", "O(n)", "O(n²)"],
        answer: 2,
        explanation: "For each of n outer iterations, the inner loop performs n iterations, producing n × n work.",
        hint: "Multiply the number of outer and inner iterations.",
      },
      {
        id: "py-arrays-strings",
        concept: "Arrays and strings",
        teachTitle: "Use two pointers to avoid extra passes",
        teachBody: "Two-pointer techniques coordinate two indexes as they move through an ordered sequence. They often replace nested comparisons with one linear scan.",
        takeaway: "Ask whether two positions can move with a useful invariant.",
        exampleTitle: "Check a palindrome from both ends",
        exampleBody: "Compare the outer characters, then move inward. A mismatch proves the string is not a palindrome.",
        sample: "def palindrome(text):\n    left, right = 0, len(text) - 1\n    while left < right:\n        if text[left] != text[right]:\n            return False\n        left += 1\n        right -= 1\n    return True",
        question: "What is the time complexity of this palindrome check?",
        options: ["O(1)", "O(n)", "O(n²)"],
        answer: 1,
        explanation: "Each character is considered at most once as the pointers move inward, so work grows linearly.",
        hint: "The pointers never move backward or revisit the full string.",
      },
      {
        id: "py-hashing",
        concept: "Hash maps",
        teachTitle: "Trade memory for fast lookup",
        teachBody: "Dictionaries and sets use hashing to provide average O(1) membership and lookup. They often turn a nested search into one pass.",
        takeaway: "Store what you have seen when future items need fast answers about the past.",
        exampleTitle: "Find a pair in one pass",
        exampleBody: "For each number, look for its complement among values already seen, then remember the current number.",
        sample: "def has_pair(nums, target):\n    seen = set()\n    for number in nums:\n        if target - number in seen:\n            return True\n        seen.add(number)\n    return False",
        question: "Why does the set improve this pair search?",
        options: ["Membership is average O(1)", "Sets sort automatically", "Sets allow duplicate values"],
        answer: 0,
        explanation: "Average constant-time membership avoids scanning all earlier numbers for every new number.",
        hint: "Compare a set membership check with a second loop.",
      },
    ],
  ),
  buildModule(
    {
      id: "py-linear-recursion",
      title: "Linear structures and recursion",
      description: "Model order with stacks, queues, linked nodes, and recursive calls.",
      level: "Advanced",
    },
    [
      {
        id: "py-stacks-queues",
        concept: "Stacks and queues",
        teachTitle: "Choose which item leaves next",
        teachBody: "A stack is last-in, first-out; a queue is first-in, first-out. The removal order should match the behavior your problem needs.",
        takeaway: "Undo uses a stack; fair arrival processing uses a queue.",
        exampleTitle: "Model browser history and jobs",
        exampleBody: "Back navigation removes the most recent page. A print queue removes the oldest waiting job.",
        sample: "Stack: A → B → C → remove C\nQueue: A → B → C → remove A",
        format: "visual",
        question: "Which structure naturally supports an Undo button?",
        options: ["Stack", "Queue", "Set"],
        answer: 0,
        explanation: "Undo reverses the most recent action first, which is last-in, first-out behavior.",
        hint: "Which action should be removed first: oldest or newest?",
      },
      {
        id: "py-linked-lists",
        concept: "Linked lists",
        teachTitle: "Connect nodes instead of shifting indexes",
        teachBody: "A linked list stores values in nodes that point to the next node. Inserting after a known node changes links without shifting later values.",
        takeaway: "Linked lists favor link changes; arrays favor indexed access.",
        exampleTitle: "Insert by rewiring two links",
        exampleBody: "The new node first points to B, then A points to the new node. The chain remains connected.",
        sample: "Before: A → B\nInsert X: A → X → B",
        format: "visual",
        question: "What is a singly linked list slow at compared with an array?",
        options: ["Reading an arbitrary index", "Inserting after a known node", "Removing the first node"],
        answer: 0,
        explanation: "A linked list must follow nodes from the head to reach an arbitrary index, making access O(n).",
        hint: "There is no direct address calculation for index 500.",
      },
      {
        id: "py-recursion",
        concept: "Recursion",
        teachTitle: "Solve a problem using a smaller version",
        teachBody: "A recursive function calls itself on a smaller input. It needs a base case that returns without another call and progress toward that case.",
        takeaway: "Base case plus smaller subproblem prevents infinite recursion.",
        exampleTitle: "Reduce factorial one number at a time",
        exampleBody: "factorial(4) becomes 4 × factorial(3) until factorial(1) returns directly.",
        sample: "def factorial(n):\n    if n <= 1:\n        return 1\n    return n * factorial(n - 1)",
        question: "What is the base case in this factorial function?",
        options: ["n <= 1", "n * factorial(n - 1)", "The function name"],
        answer: 0,
        explanation: "When n is 1 or lower, the function returns without making another recursive call.",
        hint: "Find the branch that stops calling factorial again.",
      },
    ],
  ),
  buildModule(
    {
      id: "py-trees-graphs",
      title: "Trees, heaps, and graphs",
      description: "Navigate hierarchical and network-shaped data efficiently.",
      level: "Advanced",
    },
    [
      {
        id: "py-trees",
        concept: "Trees",
        teachTitle: "Represent hierarchy with branches",
        teachBody: "A tree has a root and child nodes without cycles. Binary trees allow at most two children per node, and traversals define the visit order.",
        takeaway: "DFS explores a branch deeply; BFS explores one level at a time.",
        exampleTitle: "Choose a level-order traversal",
        exampleBody: "Breadth-first search uses a queue so all nodes at one depth are visited before the next depth.",
        sample: "      A\n    /   \\\n   B     C\n  / \\   / \\\n D   E F   G",
        format: "visual",
        question: "Which structure supports breadth-first tree traversal?",
        options: ["Queue", "Set only", "Min-heap only"],
        answer: 0,
        explanation: "A queue processes nodes in the order discovered, which preserves level order.",
        hint: "BFS is first-in, first-out across discovered nodes.",
      },
      {
        id: "py-heaps",
        concept: "Heaps",
        teachTitle: "Keep the next priority easy to reach",
        teachBody: "A heap is a partially ordered tree commonly stored in an array. A min-heap keeps the smallest item at the root and supports efficient insertion and removal.",
        takeaway: "Use a heap when you repeatedly need the next smallest or largest item.",
        exampleTitle: "Schedule the earliest deadline",
        exampleBody: "A min-heap can return the earliest deadline without sorting every task after each insertion.",
        sample: "push: O(log n)\npop smallest: O(log n)\npeek smallest: O(1)",
        format: "visual",
        question: "Which problem is a natural min-heap fit?",
        options: ["Repeatedly select the smallest job", "Check whether all values are unique once", "Store a fixed coordinate"],
        answer: 0,
        explanation: "A min-heap keeps the smallest-priority job at the root while supporting efficient updates.",
        hint: "Look for repeated access to one extreme value.",
      },
      {
        id: "py-graphs",
        concept: "Graphs",
        teachTitle: "Model relationships without a hierarchy",
        teachBody: "A graph contains vertices connected by edges. Edges may be directed, weighted, or both, allowing graphs to represent roads, dependencies, and social connections.",
        takeaway: "Use a graph when any item may connect to many other items.",
        exampleTitle: "Store neighbors with an adjacency list",
        exampleBody: "Each key maps a vertex to the vertices it can reach, using space proportional to vertices plus edges.",
        sample: "graph = {\n    \"A\": [\"B\", \"C\"],\n    \"B\": [\"D\"],\n    \"C\": [],\n    \"D\": []\n}",
        question: "Which algorithm finds shortest paths in an unweighted graph?",
        options: ["Breadth-first search", "Binary search", "Insertion sort"],
        answer: 0,
        explanation: "BFS explores by distance in edges, so the first visit to a node uses a shortest unweighted path.",
        hint: "Which traversal moves one graph level at a time?",
      },
    ],
  ),
  buildModule(
    {
      id: "py-search-sort",
      title: "Searching and sorting",
      description: "Use ordering to find answers faster and compare classic sorting strategies.",
      level: "Interview practice",
    },
    [
      {
        id: "py-binary-search",
        concept: "Binary search",
        teachTitle: "Discard half the search space",
        teachBody: "Binary search compares the target with the middle of sorted data. Every comparison removes half of the remaining candidates.",
        takeaway: "Binary search needs a sorted search space and runs in O(log n).",
        exampleTitle: "Move the correct boundary",
        exampleBody: "If the middle value is too small, every earlier value is also too small, so move left past the middle.",
        sample: "values = [2, 5, 8, 12, 20]\ntarget = 12\n# middle 8 is small → search [12, 20]",
        question: "Can ordinary binary search safely run on [8, 2, 12, 5]?",
        options: ["Yes, always", "No, the data is not sorted", "Only when the target is 8"],
        answer: 1,
        explanation: "The decision to discard half relies on ordering. Without sorted data, the target may be in the discarded half.",
        hint: "What fact lets the algorithm eliminate all values on one side?",
      },
      {
        id: "py-sorting",
        concept: "Sorting",
        teachTitle: "Understand the cost of creating order",
        teachBody: "Comparison sorts rearrange values based on pairwise order. Merge sort guarantees O(n log n) time, while simple insertion sort can be effective for small or nearly sorted inputs.",
        takeaway: "Algorithm choice depends on input size, existing order, memory, and stability needs.",
        exampleTitle: "Merge sorted halves",
        exampleBody: "Merge sort recursively sorts two halves, then combines them by repeatedly taking the smaller front value.",
        sample: "[5, 2, 8, 1]\n→ [5, 2] + [8, 1]\n→ [2, 5] + [1, 8]\n→ [1, 2, 5, 8]",
        format: "visual",
        question: "What is merge sort's worst-case time complexity?",
        options: ["O(n)", "O(n log n)", "O(n² log n)"],
        answer: 1,
        explanation: "There are log n levels of splitting, and merging across each level processes n values.",
        hint: "Multiply the number of levels by the work per level.",
      },
      {
        id: "py-greedy",
        concept: "Greedy algorithms",
        teachTitle: "Make the best local choice—with proof",
        teachBody: "A greedy algorithm commits to the best-looking current choice. It works only when those local choices can be proven to lead to a global optimum.",
        takeaway: "A plausible local choice is not enough; justify why it cannot block the optimum.",
        exampleTitle: "Select the earliest finishing interval",
        exampleBody: "For maximum non-overlapping meetings, choosing the meeting that ends first leaves the most room for later meetings.",
        sample: "Meetings: (1,3), (2,5), (4,6)\nChoose (1,3), then (4,6)",
        format: "visual",
        question: "What distinguishes a correct greedy solution from a heuristic?",
        options: ["It uses a loop", "Its local choice can be proven globally optimal", "It always sorts strings"],
        answer: 1,
        explanation: "Greedy correctness requires an exchange argument or another proof that the local choice preserves an optimal solution.",
        hint: "Fast and intuitive does not automatically mean optimal.",
      },
    ],
  ),
  buildModule(
    {
      id: "py-advanced-algorithms",
      title: "Backtracking and dynamic programming",
      description: "Explore choices systematically and reuse answers to overlapping subproblems.",
      level: "Interview practice",
    },
    [
      {
        id: "py-backtracking",
        concept: "Backtracking",
        teachTitle: "Choose, explore, and undo",
        teachBody: "Backtracking builds a candidate incrementally. When a choice cannot lead to a valid answer, it undoes that choice and explores another branch.",
        takeaway: "Backtracking is depth-first search over a decision tree with pruning.",
        exampleTitle: "Generate all subsets",
        exampleBody: "For every value, choose to include it or skip it. After exploring one choice, undo it before the other branch.",
        sample: "[1, 2]\n→ []\n→ [1]\n→ [2]\n→ [1, 2]",
        format: "visual",
        question: "What is the purpose of undoing a choice?",
        options: ["Restore state before exploring another branch", "Sort the input", "Guarantee O(1) time"],
        answer: 0,
        explanation: "Undoing restores the partial solution so a sibling decision branch starts from the correct state.",
        hint: "A later branch should not inherit a choice made only for the previous branch.",
      },
      {
        id: "py-dynamic-programming",
        concept: "Dynamic programming",
        teachTitle: "Remember overlapping subproblems",
        teachBody: "Dynamic programming applies when a problem has optimal substructure and repeats the same subproblems. Memoization caches recursion; tabulation builds answers iteratively.",
        takeaway: "Define the state, transition, base cases, and evaluation order.",
        exampleTitle: "Cache Fibonacci results",
        exampleBody: "Without caching, recursive branches recompute the same values. Memoization calculates each n once.",
        sample: "F(5) needs F(4) and F(3)\nF(4) also needs F(3)\nCache F(3) instead of repeating it",
        format: "visual",
        question: "What makes a problem a strong DP candidate?",
        options: ["Overlapping subproblems", "Only one possible input", "No reusable state"],
        answer: 0,
        explanation: "Repeated subproblems allow saved results to replace duplicated work, which is central to dynamic programming.",
        hint: "Look for the same smaller question appearing repeatedly.",
      },
      {
        id: "py-dp-state",
        concept: "Dynamic programming",
        teachTitle: "Let the state describe one answer",
        teachBody: "A DP state should contain exactly the information needed to identify a subproblem. The transition explains how smaller states produce the current state.",
        takeaway: "A clear state definition usually matters more than memorizing a template.",
        exampleTitle: "Define climbing-stairs state",
        exampleBody: "Let dp[i] be the number of ways to reach step i. The final move came from i−1 or i−2, so add those states.",
        sample: "dp[i] = dp[i - 1] + dp[i - 2]\ndp[0] = 1, dp[1] = 1",
        question: "What should dp[i] mean in the climbing-stairs example?",
        options: ["Ways to reach step i", "The largest input ever seen", "Whether Python is installed"],
        answer: 0,
        explanation: "The state represents the exact subproblem being solved: the number of ways to arrive at a particular step.",
        hint: "State the answer for one smaller input i.",
      },
    ],
  ),
];
