import { buildModule, type CourseModule } from "@/lib/course-model";

export const systemDesignModules: CourseModule[] = [
  buildModule(
    {
      id: "sd-web-networking",
      title: "Web and networking",
      description: "Follow a request through DNS, HTTP, and an API boundary.",
      level: "Foundations",
    },
    [
      {
        id: "sd-dns",
        concept: "DNS",
        teachTitle: "Turn names into addresses",
        teachBody: "DNS is the internet's directory. It resolves a domain such as bytescroll.app to an IP address a client can contact, and caches answers for a limited time called a TTL.",
        takeaway: "DNS maps a human-friendly name to a network address.",
        exampleTitle: "Resolve before connecting",
        exampleBody: "The browser checks nearby caches first. On a miss, resolvers walk the DNS hierarchy and return an address with a TTL.",
        sample: "Browser → DNS resolver → 203.0.113.8\nBrowser → 203.0.113.8",
        format: "visual",
        question: "Why does DNS use a TTL?",
        options: ["To limit how long an answer is cached", "To encrypt HTTP bodies", "To choose a database index"],
        answer: 0,
        explanation: "A TTL lets cached records expire so clients eventually learn about address changes.",
        hint: "Think about balancing fast cached lookups with changing addresses.",
      },
      {
        id: "sd-http",
        concept: "HTTP",
        teachTitle: "Give every request a clear contract",
        teachBody: "HTTP requests carry a method, path, headers, and sometimes a body. Responses return a status code, headers, and a body. The contract lets clients and servers evolve independently.",
        takeaway: "Methods express intent; status codes express outcomes.",
        exampleTitle: "Read without changing state",
        exampleBody: "GET retrieves a resource. A successful server can respond with 200 and a representation such as JSON.",
        sample: "GET /api/lessons/42\n→ 200 OK\n→ { lesson: 42 }",
        format: "visual",
        question: "Which method normally creates a new resource?",
        options: ["GET", "POST", "HEAD"],
        answer: 1,
        explanation: "POST commonly submits data that creates a subordinate resource or starts an operation.",
        hint: "Choose the method used to submit a new item.",
      },
      {
        id: "sd-api-contracts",
        concept: "APIs",
        teachTitle: "Design stable boundaries",
        teachBody: "An API defines inputs, outputs, errors, and compatibility rules. Good contracts validate input, use consistent naming, paginate large collections, and change without surprising old clients.",
        takeaway: "An API is a promise between independently changing systems.",
        exampleTitle: "Paginate an unbounded list",
        exampleBody: "A cursor points after the last returned item, avoiding a giant response and remaining steadier than large numeric offsets when new rows arrive.",
        sample: "GET /posts?limit=20&after=p_81\n→ items: [...]\n→ next_cursor: p_61",
        format: "visual",
        question: "What is the main reason to paginate a feed API?",
        options: ["Bound response size and work", "Remove authentication", "Guarantee zero latency"],
        answer: 0,
        explanation: "Pagination limits data transfer and server work for collections that may keep growing.",
        hint: "Imagine returning ten million posts in one response.",
      },
    ],
  ),
  buildModule(
    {
      id: "sd-data-storage",
      title: "Data and storage",
      description: "Choose databases, indexes, and consistency guarantees deliberately.",
      level: "Intermediate",
    },
    [
      {
        id: "sd-sql-nosql",
        concept: "Databases",
        teachTitle: "Start from access patterns",
        teachBody: "Relational databases are strong at structured relationships, constraints, and transactions. NoSQL systems offer different models and scaling tradeoffs. Choose from the reads, writes, relationships, and guarantees you need.",
        takeaway: "Database choice follows access patterns, not fashion.",
        exampleTitle: "Keep payments relational",
        exampleBody: "Orders, charges, and refunds benefit from constraints and transactions that keep related updates consistent.",
        sample: "orders ──< payments\n   │\n   └──< order_items",
        format: "visual",
        question: "Which workload most strongly benefits from relational transactions?",
        options: ["A payment ledger", "A static image archive", "A disposable cache"],
        answer: 0,
        explanation: "A payment ledger needs related writes to succeed or fail together and preserve strict invariants.",
        hint: "Look for the workload where partial updates are dangerous.",
      },
      {
        id: "sd-indexes",
        concept: "Indexes",
        teachTitle: "Trade extra writes for faster reads",
        teachBody: "An index stores selected columns in a search-friendly structure. It avoids scanning every row but consumes space and must be updated on writes.",
        takeaway: "Index fields used by important filters, joins, and sort orders.",
        exampleTitle: "Serve a user's recent posts",
        exampleBody: "A composite index on user_id and created_at supports filtering by user and reading newest records first.",
        sample: "INDEX (user_id, created_at DESC)\nquery: user_id = 7 ORDER BY created_at DESC",
        format: "visual",
        question: "What is a common cost of adding an index?",
        options: ["Slower writes and extra storage", "All reads become slower", "Rows lose their schema"],
        answer: 0,
        explanation: "Each relevant write must also maintain the index, and the index occupies storage.",
        hint: "The database maintains another data structure.",
      },
      {
        id: "sd-transactions",
        concept: "Transactions",
        teachTitle: "Protect multi-step invariants",
        teachBody: "A transaction groups operations into one logical unit. ACID properties help ensure partial failures do not expose half-finished state, though stronger isolation can reduce concurrency.",
        takeaway: "Use a transaction when several changes must be correct together.",
        exampleTitle: "Move money atomically",
        exampleBody: "Debiting one balance and crediting another should commit together. If either write fails, both roll back.",
        sample: "BEGIN\n  debit(A, 50)\n  credit(B, 50)\nCOMMIT or ROLLBACK",
        format: "visual",
        question: "What should happen if the credit fails during a transfer?",
        options: ["Keep the debit", "Roll back the transaction", "Retry only in the browser forever"],
        answer: 1,
        explanation: "Rolling back prevents money from disappearing when only half the transfer succeeds.",
        hint: "The invariant is that total money must not change.",
      },
    ],
  ),
  buildModule(
    {
      id: "sd-scaling",
      title: "Scaling and delivery",
      description: "Spread traffic and data across more than one machine.",
      level: "Intermediate",
    },
    [
      {
        id: "sd-load-balancing",
        concept: "Load balancing",
        teachTitle: "Distribute requests across servers",
        teachBody: "A load balancer chooses a healthy backend for each request. This raises capacity and availability, especially when application servers remain stateless.",
        takeaway: "Health checks and stateless servers make horizontal scaling practical.",
        exampleTitle: "Remove one unhealthy server",
        exampleBody: "Health checks stop new traffic from reaching a failed instance while healthy instances keep serving users.",
        sample: "Users → Load balancer → App A ✓\n                      → App B ✕\n                      → App C ✓",
        format: "visual",
        question: "Why are stateless app servers easier to load balance?",
        options: ["Any healthy server can handle the next request", "They need no database", "They eliminate network failures"],
        answer: 0,
        explanation: "When session state is external, requests do not have to return to one special server.",
        hint: "Ask whether the next request depends on memory inside one instance.",
      },
      {
        id: "sd-cdn",
        concept: "CDNs",
        teachTitle: "Move cacheable content near users",
        teachBody: "A CDN serves static or cacheable responses from edge locations. Shorter network distance reduces latency and offloads the origin, but invalidation and freshness still need a policy.",
        takeaway: "A CDN improves delivery; it does not replace the source of truth.",
        exampleTitle: "Cache an image at the edge",
        exampleBody: "The first regional request fetches from the origin. Later nearby requests hit the edge cache until the entry expires.",
        sample: "User → Edge HIT\n          ↘ Edge MISS → Origin",
        format: "visual",
        question: "Which asset is the safest CDN candidate?",
        options: ["Versioned public logo.png", "A user's private live balance", "An uncommitted database row"],
        answer: 0,
        explanation: "A versioned public image is stable, cacheable, and contains no per-user private state.",
        hint: "Choose content that is public and changes only under a new name.",
      },
      {
        id: "sd-partitioning",
        concept: "Partitioning",
        teachTitle: "Split data without creating hotspots",
        teachBody: "Replication copies data for availability and reads. Partitioning, or sharding, divides data across nodes for capacity. The partition key controls distribution and query cost.",
        takeaway: "A good partition key spreads load and matches common queries.",
        exampleTitle: "Shard by user id",
        exampleBody: "Hashing user_id spreads many users across shards. A single celebrity can still become a hot key if their traffic dominates.",
        sample: "hash(user_id) % 3\n0 → shard A\n1 → shard B\n2 → shard C",
        format: "visual",
        question: "What makes a partition key risky?",
        options: ["Most traffic lands on one value", "It has a clear type", "It appears in queries"],
        answer: 0,
        explanation: "A heavily skewed key overloads one partition while others remain underused.",
        hint: "Think about even distribution of both data and requests.",
      },
    ],
  ),
  buildModule(
    {
      id: "sd-async",
      title: "Asynchronous systems",
      description: "Use queues, events, and idempotency to decouple work safely.",
      level: "Intermediate",
    },
    [
      {
        id: "sd-queues",
        concept: "Queues",
        teachTitle: "Buffer work between services",
        teachBody: "A message queue lets producers hand off work without waiting for consumers to finish. It absorbs bursts, enables retries, and creates eventual rather than immediate completion.",
        takeaway: "Queues trade immediate completion for resilience and independent scaling.",
        exampleTitle: "Process emails in the background",
        exampleBody: "The API acknowledges the signup quickly. Workers consume email jobs at their own sustainable rate.",
        sample: "API → [email jobs] → Worker pool\n  ↘ fast response",
        format: "visual",
        question: "What happens when producers briefly outpace consumers?",
        options: ["The queue backlog grows", "Every database disappears", "DNS changes automatically"],
        answer: 0,
        explanation: "The queue buffers the burst, but sustained growth still requires more consumers or less production.",
        hint: "A queue is a waiting line.",
      },
      {
        id: "sd-pub-sub",
        concept: "Events",
        teachTitle: "Let many consumers react to one event",
        teachBody: "Publish-subscribe delivers an event to multiple independent subscribers. It reduces direct coupling, but event schemas, ordering, replay, and duplicate handling become design concerns.",
        takeaway: "Events describe something that happened; subscribers choose their reaction.",
        exampleTitle: "Fan out an order event",
        exampleBody: "Inventory, analytics, and notifications can each consume OrderPlaced without the checkout service calling each one directly.",
        sample: "OrderPlaced → Inventory\n            → Analytics\n            → Notifications",
        format: "visual",
        question: "What is a benefit of publish-subscribe?",
        options: ["Independent consumers can react", "Events are never duplicated", "All work is synchronous"],
        answer: 0,
        explanation: "Subscribers can evolve and scale separately while receiving the same published event.",
        hint: "One event can have more than one interested listener.",
      },
      {
        id: "sd-idempotency",
        concept: "Idempotency",
        teachTitle: "Make retries safe",
        teachBody: "An idempotent operation has the same intended effect when repeated. Clients attach a stable idempotency key, and the server remembers the first result instead of performing the action twice.",
        takeaway: "Retries are safe only when duplicate effects are controlled.",
        exampleTitle: "Charge once after a timeout",
        exampleBody: "If the response is lost, the client retries with the same key. The payment service returns the stored result rather than charging again.",
        sample: "POST /charges\nIdempotency-Key: order_42\nretry → same result, no second charge",
        format: "visual",
        question: "Which value makes the best idempotency key?",
        options: ["A stable unique operation id", "The current second", "A random value on every retry"],
        answer: 0,
        explanation: "Every attempt for one logical operation must reuse the same unique key.",
        hint: "The server needs to recognize that two requests mean the same action.",
      },
    ],
  ),
  buildModule(
    {
      id: "sd-distributed",
      title: "Distributed systems",
      description: "Reason about consistency, coordination, and partial failure.",
      level: "Advanced",
    },
    [
      {
        id: "sd-consistency",
        concept: "Consistency",
        teachTitle: "Choose behavior during partitions",
        teachBody: "In a network partition, a distributed system cannot guarantee both every request succeeds and every read sees the latest write. CAP is a tradeoff during partition, not a database ranking.",
        takeaway: "State the consistency and availability behavior your feature actually needs.",
        exampleTitle: "Protect a unique username",
        exampleBody: "A system may reject or delay a signup during uncertainty rather than allow two people to claim the same unique name.",
        sample: "Partition detected\nCP choice → reject uncertain write\nAP choice → accept, reconcile later",
        format: "visual",
        question: "During a partition, what does a CP system prioritize?",
        options: ["Consistent responses over accepting every request", "Unlimited storage", "Zero replication"],
        answer: 0,
        explanation: "A CP system may refuse some requests so it does not return conflicting or stale state.",
        hint: "C means consistency; P is the partition already happening.",
      },
      {
        id: "sd-leaders",
        concept: "Consensus",
        teachTitle: "Agree on one ordered history",
        teachBody: "Consensus protocols help nodes agree on a leader and an ordered log despite failures. Quorums prevent two isolated minorities from both safely committing conflicting histories.",
        takeaway: "Consensus coordinates critical metadata; it is not a free performance boost.",
        exampleTitle: "Commit with a majority",
        exampleBody: "In a five-node group, a write acknowledged by three nodes intersects any other majority, preserving an agreed history.",
        sample: "5 nodes → quorum 3\nwrite: A ✓ B ✓ C ✓ D ? E ? → committed",
        format: "visual",
        question: "Why do quorums usually use a majority?",
        options: ["Any two majorities overlap", "A majority removes latency", "Minorities store no data"],
        answer: 0,
        explanation: "Overlapping majorities contain at least one node that can carry knowledge of the latest committed state.",
        hint: "Compare two groups that each contain more than half the nodes.",
      },
      {
        id: "sd-locks",
        concept: "Coordination",
        teachTitle: "Use distributed locks sparingly",
        teachBody: "A distributed lock grants temporary ownership of a resource. Leases need expiry, ownership tokens, and careful handling of pauses because a client may continue after its lease has expired.",
        takeaway: "Prefer ownership tokens and idempotency; a lock alone cannot stop a stale client.",
        exampleTitle: "Reject a stale writer",
        exampleBody: "A fencing token increases with each lease. Storage rejects writes carrying a token older than the newest one it has seen.",
        sample: "worker A token 8 (expired) → rejected\nworker B token 9          → accepted",
        format: "visual",
        question: "What problem does a fencing token solve?",
        options: ["A stale lock holder writing late", "A missing CSS file", "A slow DNS cache"],
        answer: 0,
        explanation: "The resource can reject operations from an old owner even if that process still believes it holds the lock.",
        hint: "Think about a paused worker waking after its lease expired.",
      },
    ],
  ),
  buildModule(
    {
      id: "sd-reliability",
      title: "Reliability and operations",
      description: "Design for failure, observe reality, and recover deliberately.",
      level: "Advanced",
    },
    [
      {
        id: "sd-resilience",
        concept: "Resilience",
        teachTitle: "Stop failures from cascading",
        teachBody: "Timeouts bound waiting. Retries handle transient failures but need exponential backoff and jitter. Circuit breakers temporarily stop calls when a dependency is failing.",
        takeaway: "Every remote call needs a timeout; every retry needs a budget.",
        exampleTitle: "Back off instead of stampeding",
        exampleBody: "Clients wait progressively longer and add randomness, preventing synchronized retries from overwhelming a recovering service.",
        sample: "attempt 1 → wait ~1s\nattempt 2 → wait ~2s\nattempt 3 → wait ~4s",
        format: "visual",
        question: "Why add jitter to retry delays?",
        options: ["Spread retry traffic over time", "Guarantee every call succeeds", "Replace authentication"],
        answer: 0,
        explanation: "Randomness prevents many clients from retrying at exactly the same moments.",
        hint: "Imagine thousands of clients sharing one fixed retry timer.",
      },
      {
        id: "sd-observability",
        concept: "Observability",
        teachTitle: "Explain a system from its outputs",
        teachBody: "Metrics show trends, logs capture events, and traces connect work across services. Useful alerts focus on user impact through latency, traffic, errors, and saturation.",
        takeaway: "Observe user-facing symptoms and keep enough context to find causes.",
        exampleTitle: "Trace one slow request",
        exampleBody: "A trace reveals that most latency came from the catalog database rather than the API gateway.",
        sample: "request 900ms\n├─ gateway 20ms\n├─ catalog DB 820ms\n└─ render 60ms",
        format: "visual",
        question: "Which signal best connects one request across services?",
        options: ["A distributed trace", "A logo file", "A DNS TXT record"],
        answer: 0,
        explanation: "A distributed trace links spans from the same request across service boundaries.",
        hint: "Choose the signal built from parent and child spans.",
      },
      {
        id: "sd-recovery",
        concept: "Disaster recovery",
        teachTitle: "Define acceptable loss and downtime",
        teachBody: "RPO states how much recent data loss is acceptable. RTO states how long recovery may take. Backups only count when restore procedures are tested.",
        takeaway: "Recovery targets turn 'highly available' into testable requirements.",
        exampleTitle: "Translate business tolerance",
        exampleBody: "An RPO of five minutes needs backups or replication frequent enough to lose no more than roughly five minutes of accepted writes.",
        sample: "RPO = max data loss\nRTO = max recovery time",
        format: "visual",
        question: "Which target limits acceptable downtime?",
        options: ["RTO", "RPO", "TTL"],
        answer: 0,
        explanation: "Recovery Time Objective is the target duration for restoring service.",
        hint: "The T in RTO stands for time.",
      },
    ],
  ),
  buildModule(
    {
      id: "sd-security",
      title: "Security and abuse control",
      description: "Protect identities, secrets, and shared capacity.",
      level: "Advanced",
    },
    [
      {
        id: "sd-auth",
        concept: "Authentication",
        teachTitle: "Separate identity from permission",
        teachBody: "Authentication proves who a caller is. Authorization decides what that identity may do. Sessions or tokens carry identity, while server-side checks enforce permissions on every protected action.",
        takeaway: "Never trust the interface to enforce authorization.",
        exampleTitle: "Check ownership on the server",
        exampleBody: "Hiding an Edit button is useful UX, but the API must still verify that the signed-in user owns the document.",
        sample: "request + identity\n→ authenticate\n→ authorize resource action\n→ allow or deny",
        format: "visual",
        question: "Which check decides whether Maya may edit document 42?",
        options: ["Authorization", "DNS resolution", "Compression"],
        answer: 0,
        explanation: "Authorization evaluates whether an authenticated identity has permission for a specific action and resource.",
        hint: "Identity is known; now decide what it may do.",
      },
      {
        id: "sd-rate-limits",
        concept: "Rate limiting",
        teachTitle: "Protect finite capacity",
        teachBody: "Rate limiting bounds requests per identity, key, or IP. Token buckets allow controlled bursts while enforcing a long-term rate, and limits need clear responses and retry guidance.",
        takeaway: "Rate limits protect fairness and availability, not just billing.",
        exampleTitle: "Allow a small burst",
        exampleBody: "A bucket starts with tokens. Each request consumes one, and tokens refill at a steady rate up to the bucket capacity.",
        sample: "bucket capacity: 10\nrefill: 2 tokens/sec\nrequest: consume 1 or return 429",
        format: "visual",
        question: "What does HTTP 429 mean?",
        options: ["Too many requests", "Resource created", "Permanent redirect"],
        answer: 0,
        explanation: "429 tells the client it has exceeded an allowed request rate.",
        hint: "It is the standard rate-limit response.",
      },
      {
        id: "sd-secrets",
        concept: "Secrets",
        teachTitle: "Keep credentials out of clients and code",
        teachBody: "Secrets belong in managed server-side configuration with limited access, rotation, and auditing. Anything shipped to a browser can be inspected by its user.",
        takeaway: "A browser environment variable is public if it reaches the client bundle.",
        exampleTitle: "Proxy a paid service safely",
        exampleBody: "The browser calls your backend. The backend reads the secret, authorizes the user, calls the provider, and returns only necessary data.",
        sample: "Browser → Your API → Provider\n             secret stays here ↑",
        format: "visual",
        question: "Where should a private API key be stored?",
        options: ["Server-side secret storage", "A public JavaScript bundle", "An HTML comment"],
        answer: 0,
        explanation: "Server-side secret storage keeps the key out of code delivered to users and supports controlled access and rotation.",
        hint: "Users can inspect everything their browser downloads.",
      },
    ],
  ),
  buildModule(
    {
      id: "sd-case-studies",
      title: "Design case studies",
      description: "Combine the pieces in interview-sized architecture exercises.",
      level: "Interview practice",
    },
    [
      {
        id: "sd-url-shortener",
        concept: "URL shortener",
        teachTitle: "Design a read-heavy redirect service",
        teachBody: "Clarify scale and custom aliases, generate unique short keys, store key-to-URL mappings, cache popular redirects, and keep redirects fast even if analytics runs asynchronously.",
        takeaway: "Separate the critical redirect path from optional analytics work.",
        exampleTitle: "Keep redirects short",
        exampleBody: "The service checks cache, falls back to storage, returns a redirect, and publishes a click event without blocking the user.",
        sample: "GET /x7a → Cache → DB fallback → 302\n                  ↘ click event → analytics",
        format: "visual",
        question: "Which work should stay off the redirect critical path?",
        options: ["Click analytics aggregation", "Looking up the destination", "Returning the redirect"],
        answer: 0,
        explanation: "Analytics can be emitted asynchronously so it does not increase user-visible redirect latency.",
        hint: "Choose work that can happen after the user is sent onward.",
      },
      {
        id: "sd-news-feed",
        concept: "News feed",
        teachTitle: "Choose when to assemble a feed",
        teachBody: "Fan-out on write precomputes followers' feeds for fast reads but makes celebrity posts expensive. Fan-out on read computes later. Real systems often combine both strategies.",
        takeaway: "Feed design trades write amplification for read latency.",
        exampleTitle: "Use a hybrid fan-out",
        exampleBody: "Precompute ordinary users' posts, but merge celebrity posts at read time to avoid writing millions of inbox entries at once.",
        sample: "normal post → follower inboxes\ncelebrity post → merge on read",
        format: "visual",
        question: "Why avoid fan-out on write for a celebrity account?",
        options: ["One post may trigger millions of writes", "Followers cannot read caches", "Posts have no timestamps"],
        answer: 0,
        explanation: "Very large follower counts turn one publish action into a huge burst of downstream writes.",
        hint: "Count how many follower inboxes one post must update.",
      },
      {
        id: "sd-chat",
        concept: "Chat system",
        teachTitle: "Deliver messages in a useful order",
        teachBody: "A chat system needs persistent connections, durable message storage, delivery acknowledgements, per-conversation ordering, offline sync, and a clear model for delivered versus read state.",
        takeaway: "Define ordering scope and delivery guarantees before choosing technology.",
        exampleTitle: "Order within each conversation",
        exampleBody: "A sequence number per conversation gives clients a stable way to sort, detect gaps, and request missing messages.",
        sample: "client ↔ gateway → conversation shard\n                    ↘ push/offline queue",
        format: "visual",
        question: "Which ordering guarantee is usually practical for chat?",
        options: ["Order within each conversation", "One global order for every message", "No ordering at all"],
        answer: 0,
        explanation: "Per-conversation order matches user expectations without forcing unrelated chats through one global bottleneck.",
        hint: "Two unrelated conversations do not need to agree on one timeline.",
      },
    ],
  ),
];
